server:
  port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/songs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver